# Generated by Django 3.0.8 on 2020-07-26 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertorData',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('email', models.EmailField(
                    blank=True, max_length=254, null=True)),
                ('source', models.TextField()),
                ('output', models.FileField(
                    upload_to='',
                    validators=[
                        django.core.validators.FileExtensionValidator(
                            allowed_extensions=['pdf'])])),
                ('is_url', models.BooleanField(default=False)),
                ('domain', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
